export default {
    logo : require ('../assets/images/logo.png.webp'),
    carousel1 : require ('../assets/images/carousel1.jpg'),
    carousel2 : require ('../assets/images/carousel2.jpg'),
    carousel3 : require ('../assets/images/carousel3.webp'),
    banner2 : require ('../assets/images/banner-02.jpg'),
    banner5 : require ('../assets/images/banner-05.webp'),
    watch : require ('../assets/images/item-05.jpg'),
    banner3 : require ('../assets/images/banner-03.webp'),
    banner7 : require ('../assets/images/banner-07.jpg'),
    banner4 : require ('../assets/images/banner-04.jpg'),
    banner9 : require ('../assets/images/banner-09.webp'),
    img1 : require ('../assets/images/img1.webp'),
    img2 : require ('../assets/images/img2.webp'),
    img3 : require ('../assets/images/img3.webp'),
    img4 : require ('../assets/images/img4.webp'),
    img5 : require ('../assets/images/img5.webp'),
    img6 : require ('../assets/images/img6.webp'),
    img7 : require ('../assets/images/img7.webp'),
    img8 : require ('../assets/images/img8.webp'),
    banner8 : require ('../assets/images/banner-08.jpg'),
    item1 : require ('../assets/images/item1.jpg'),
    item2 : require ('../assets/images/item2.jpg'),
    item3 : require ('../assets/images/item3.jpg'),
    item4 : require ('../assets/images/item4.jpg'),
    item5 : require ('../assets/images/item5.jpg'),
    blog1 :require ('../assets/images/blog-01.jpg'),
    blog2 :require ('../assets/images/blog-02.jpg'),
    blog3 :require ('../assets/images/blog-03.jpg'),
    aboutbanner : require ('../assets/images/about_top.webp'),

}